### ISSUE TITLE
Lighting system

### ISSUE THREAD

**Issue by vainiovano** [opensuspect/opensuspect-legacy#107]
The players shouldn't be able to see players through walls, but they should still be able see the darkened environment. The players should probably have a limited visual range.

**Comment by moxvallix** [comment]
Maybe make the view distance a variable like in Among Us?

**Comment by Noobidoo** [comment]
I have done this previously with 2 sets of light masks. One that hides the players but not the environment. and one that obfuscates the view so that you could not see what was behind you.

For the obfuscation i just used a polygon that was attached to the player. Here you could use a circle that you set the radius based on distance a variable

**Comment by vincens2005** [comment]
The view distance can be controlled by setting the scale of the light in player.tscn
