### ISSUE TITLE
Maintenance tasks

### ISSUE THREAD

**Issue by nicemicro** [opensuspect/opensuspect-legacy#198]
A task type, that is never "started" or "finished", but constantly emits an output value based on some random input and some setting in the task interface (check https://github.com/opensuspect/design-document/blob/main/general_gameplay.md for reference).
The input value(s) should be constantly managed by the server, and task, where the setting is available, should provide the same interface with all players, so that should also be managed by the server. The output value should be also available to tasks that depend on the maintenance task, and certain values should trigger events such as warning sirens or even win / loss conditions.

There is a mock implementation of a gas valve task where the output should be regulated with a randomly changing input in [PR#192](https://github.com/opensuspect/opensuspect/pull/192).

**Comment by TheSecondReal0** [comment]
Maintenance tasks should probably be implemented as a collection of map nodes (gas valve where you open the task and a node that displays pressure) and go through the map interaction system rather than the task system. They don't really work like normal "tasks", they're not required for victory and literally anyone can just walk up and do them.

**Comment by Damjan94** [comment]
May I be assigned this issue? It will definitely take me days to finish it(hopefully less than a week)
